### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by pmoust** [discordapp/punt#6]
Currently there's no dependency management.

Some library pinning and/or dep vendoring would be helpful.

**Comment by Aareon** [comment]
All it needs is a `requirements.txt`, no?

**Comment by b1naryth1ef** [comment]
@pmoust the main reason we don't have anything at the moment is there is realistically only two dependencies, elastic (which is sanely versioned by tag via gopkg) and `github.com/oschwald/geoip2-golang` (which hasn't been updated since April 2017).

I'd be open to vendoring geoip2 if someone would like to PR that, I think for now depending on the elastic tag _should_ be good (and if it breaks we can revisit).

**Comment by b1naryth1ef** [comment]
Ah I forgot `github.com/DataDog/datadog-go/statsd`, which can probably also be vendored.
